# Site
repository: sammylie83/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lie Samsudin Skom
title: Senior Backend Developer
email: sammylie83@gmail.com
website: https://sammylie83.github.io/modern-resume-theme/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  sammylie83
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: sammylie83
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
# icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Lie Samsudin, my nickname sammylie and I'm a Senior Backend Developer. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Java Web Base(JSP, Servlet, EJB, CSS, Javascript)</mark> and <mark>Framework Grails</mark> and <mark>Framework CodeIgniter</mark> and <mark>Framework Spring Boot</mark>and <mark>Database Oracle, MYSQL, Postgree SQL, SQL Lite</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sammylie83
        # link_text: Project Website
        additional_links:
          - title:  sammylie83/modern-resume-theme
            icon: fab fa-github
            url: github.com/sammylie83/modern-resume-theme
          # - title:  Github page for project (eg. sammylie83/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sammylie83.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>Java web base ( servlet, jsp, ejb, xml, css, html, javascript) and VB and Framework CodeIgniter </mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
            - layout: left
              title: PT Sahabat Mikro Fintek
              link: https://www.samir.co.id
              # link_text: boringcompany.com
              sub_title: Senior IT Backend Developer
              caption: Mei 2023 - Present
              quote: >
                 * Design, develop and maintain the server-side-logic and database of the company's web applications
                 * Write and optimize complex SQL queries for database operations
                 * Collaborate with front-end developers to integrate their work with the backend
                 * Troubleshoot and debug production issues
                 * Ensure high performance and responsiveness of the applications
                 * Manage the interchange of data between the server and the users
                 * Build reusable code and libraries for future use
                 * Implement security and data protection measures
                 * Stay up-to-date with emerging trends and technologies in backend development
                 
              # description: | # this will include new lines to allow paragraphs
              #    Every company needs its programming properly administered and The Sahabat Mikro Fintek Compay is no exception. I enjoy driving the company to try new technologies.
      
            - layout: left
              title: PT Asuransi Sinar Mas TBK
              link: https://www.sinarmas.co.id/
              # link_text: boringcompany.com
              sub_title: Senior IT Backend Developer / Backend Java Spring Boot
              caption: Nov 2020 - April 2023
              quote: >
                 * Manage the operational eclaim system for java applications, and monitor databases, servers so that the system runs properly
                 * Manage Medicare Reconsile
                 * Manage applications for sending email and uploading cards
                 * Create views, functions and procedures for Oracle SQL to quickly manage
                 * Java application errors and repair data so users can use the application
                 * Creating Oracle plsql procedures related to operational jobs
                 * Add and create java, jsp, servlet and ejb code according to user requests (change requests)
              # description: | # this will include new lines to allow paragraphs
              #    Every company needs its programming properly administered and The Sahabat Mikro Fintek Compay is no exception. I enjoy driving the company to try new technologies.

             - layout: left
               title: PT Smart Technologi ( Indosmart Group)
               link: https://www.indosmart.co.id/
               # link_text: boringcompany.com
               sub_title: Senior IT Backend Developer Java
               caption: Nov 2015 - Nov 2020
               quote: >
                 * Maintenance aplikasi java web base grails framework
                 * H2H project java with json and xmlrpc such as payment, token, and topup
                 * Handle VB 6 aplikasi Front End User
                 * Develop Project ISO8385 Such As Payment
                 * Handle project Soap for Topup
                 * Handle Bug Error Application Payment Topup
                 * Handle Framework Java GRAILS for Reporting
                 * Develop Anymore Project API with JSON
  
             - layout: left
               title: PT Trikomsel Oke TBK
               link: https://www.trikomseloke.com/
               # link_text: boringcompany.com
               sub_title: IT Backend Developer Java
               caption: Feb 2011 - Feb 2015
               quote: >
                 * Maintenance Web base php pemograman (framework Codeigniter)
                 * Maintenance aplikasi vb barcode handphone
                 * Maintenance Web base java (Servlet, JSP, EJB)
           
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indonusa Esa Unggul University
        caption: 2002 - 2007
        sub_title: Teknik Informatika
        quote: >
           Esa Unggul University (UEU) was founded in 1993 under the auspices of the Kemala Bangsa Education Foundation and is a leading private university and is one of the best private universities in Indonesia.
        description: | # this will include new lines to allow paragraphs
          Esa Unggul University (UEU) is a leading private university and is one of the best private universities in Indonesia which has a VISION, namely to become a world class university based on intellect, creativity and entrepreneurship that excels in mutual management (process) and results (output) of activities Tri Dharma of Higher Education. And has a MISSION: Providing quality and relevant education, Creating a conducive academic atmosphere, Creating leaders with high character and competitiveness.

         
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Swiming
      - Gaming 
      - Singing
      
      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
